from repository import repo_create


def cmd_add(args): ...
def cmd_cat_file(args): ...
def cmd_check_ignore(args): ...
def cmd_checkout(args): ...
def cmd_commit(args): ...
def cmd_hash_object(args): ...
def cmd_init(args):
    repo_create(args.path)


def cmd_log(args): ...
def cmd_ls_files(args): ...
def cmd_ls_tree(args): ...
def cmd_rev_parse(args): ...
def cmd_rm(args): ...
def cmd_show_ref(args): ...
def cmd_status(args): ...
def cmd_tag(args): ...
